In [1]:
import gym  # 导入 Gym 的 Python 接口环境包
env = gym.make('CartPole-v0')  # 构建实验环境
env.reset()  # 重置一个回合
for _ in range(1000):
    env.render()  # 显示图形界面
    action = env.action_space.sample() # 从动作空间中随机选取一个动作
    env.step(action) # 用于提交动作，括号内是具体的动作
env.close() # 关闭环境

/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/envs/registration.py:594: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  f"The environment {id} is out of date. You should consider "
/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_ste

In [1]:
# 观察observation长啥样
import gym  
env = gym.make('CartPole-v0')  
env.reset()  
for _ in range(1000):
    env.render()  
    action = env.action_space.sample() 
    observation, reward, done, info = env.step(action)
    print(observation)
env.close()   

/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/envs/registration.py:594: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  f"The environment {id} is out of date. You should consider "
/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_ste

[-0.02021375 -0.17033994  0.01531106  0.29969332]
[-0.02362055  0.02456046  0.02130492  0.01187826]
[-0.02312934 -0.17086045  0.02154249  0.31120628]
[-0.02654655  0.02394806  0.02776661  0.0253943 ]
[-0.02606759  0.21866104  0.0282745  -0.25840023]
[-0.02169437  0.02314709  0.02310649  0.04306507]
[-0.02123142  0.21793021  0.0239678  -0.24223892]
[-0.01687282  0.41270176  0.01912302 -0.52726644]
[-0.00861879  0.6075495   0.00857769 -0.8138628 ]
[ 0.0035322   0.4123111  -0.00769957 -0.5184942 ]


/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/core.py:50: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  "You are calling render method, "


[ 0.01177843  0.6075406  -0.01806945 -0.81359345]
[ 0.02392924  0.41267073 -0.03434132 -0.52664846]
[ 0.03218265  0.60825866 -0.04487429 -0.8299517 ]
[ 0.04434783  0.8039643  -0.06147332 -1.1364033 ]
[ 0.06042711  0.9998342  -0.08420139 -1.4477149 ]
[ 0.08042379  1.1958846  -0.11315569 -1.7654746 ]
[ 0.10434149  1.002209   -0.14846519 -1.510016  ]
[ 0.12438567  1.1987852  -0.1786655  -1.8451251 ]
[ 0.14836137  1.0060265  -0.215568   -1.6128384 ]
[ 0.1684819   1.2029431  -0.24782477 -1.964264  ]


/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/envs/classic_control/cartpole.py:180: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  "You are calling 'step()' even though this "


[ 0.19254076  1.0111526  -0.28711006 -1.7574846 ]
[ 0.21276382  1.2081603  -0.32225975 -2.124155  ]
[ 0.23692702  1.0173528  -0.36474285 -1.9457904 ]
[ 0.2572741   1.2141045  -0.40365866 -2.3263757 ]
[ 0.28155616  1.0242325  -0.45018616 -2.1799366 ]
[ 0.30204082  0.83532894 -0.4937849  -2.0527422 ]
[ 0.3187474   0.647334   -0.53483975 -1.94378   ]
[ 0.33169407  0.46017998 -0.5737153  -1.8521056 ]
[ 0.34089768  0.27379677 -0.61075747 -1.7768638 ]
[ 0.34637362  0.08811452 -0.6462947  -1.7172991 ]
[ 0.3481359  -0.09693435 -0.6806407  -1.672763  ]
[ 0.34619722  0.09783982 -0.71409595 -2.0848334 ]
[ 0.348154   -0.08715522 -0.7557926  -2.067687  ]
[ 0.3464109 -0.2716301 -0.7971464 -2.0679603]
[ 0.3409783  -0.45567632 -0.83850557 -2.0853739 ]
[ 0.33186477 -0.6393893  -0.8802131  -2.1197667 ]
[ 0.319077  -0.8228704 -0.9226084 -2.171091 ]
[ 0.30261958 -0.6333257  -0.96603024 -2.5771163 ]
[ 0.28995308 -0.44609714 -1.0175725  -2.9786496 ]
[ 0.28103113 -0.63230884 -1.0771456  -3.0820324 ]
[ 0.2683

In [2]:
# 查看Gym库中注册的环境
from gym import envs
env_specs = envs.registry.all()
envs_ids = [env_spec.id for env_spec in env_specs]
print(envs_ids)

['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4']


/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/envs/registration.py:422: UserWarning: WARN: The `registry.all` method is deprecated. Please use `registry.values` instead.
  "The `registry.all` method is deprecated. Please use `registry.values` instead."


# 与 Gym 交互

In [3]:
# 与 Gym 交互
import gym
env = gym.make('MountainCar-v0')
print('观测空间 = {}'.format(env.observation_space))
print('动作空间 = {}'.format(env.action_space))
print('观测范围 = {} ~ {}'.format(env.observation_space.low,
        env.observation_space.high))
print('动作数 = {}'.format(env.action_space.n))

观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3


/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in f

In [4]:
# 创建智能体类 (目前并非强化学习的智能体, 它只能根据特定数学表达式来决策)
class SimpleAgent:
    def __init__(self, env):
        pass
    
    def decide(self, observation): # 决策
        position, velocity = observation
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03,
                0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07
        if lb < velocity < ub:
            action = 2
        else:
            action = 0
        return action # 返回动作

    def learn(self, *args): # 学习
        pass
    
agent = SimpleAgent(env)

In [5]:
# 该函数可以让智能体与环境交互一个 回合 
def play(env, agent, render=False, train=False):
    episode_reward = 0. # 记录回合总奖励，初始值为0
    observation = env.reset() # 重置游戏环境，开始新回合
    while True: # 不断循环，直到回合结束
        if render: # 判断是否显示
            env.render() # 显示图形界面
        action = agent.decide(observation)
        next_observation, reward, done, _ = env.step(action) # 执行动作
        episode_reward += reward # 收集回合奖励
        if train: # 判断是否训练智能体
            agent.learn(observation, action, reward, done) # 学习
        if done: # 回合结束，跳出循环
            break
        observation = next_observation
    return episode_reward # 返回回合总奖励

In [6]:
# 执行一次交互
env.seed(3) # 设置随机种子，让结果可复现
episode_reward = play(env, agent, render=True)
print('回合奖励 = {}'.format(episode_reward))
env.close() # 关闭图形界面

/Users/nullptr/anaconda3/envs/joyrl/lib/python3.7/site-packages/gym/core.py:257: DeprecationWarning: WARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed)` instead.
  "Function `env.seed(seed)` is marked as deprecated and will be removed in the future. "


回合奖励 = -105.0


In [9]:
# 执行多个回合, 计算平均奖励
import numpy as np
episode_rewards = [play(env, agent) for _ in range(100)]
print('平均回合奖励 = {}'.format(np.mean(episode_rewards)))

平均回合奖励 = -107.58


出于习惯使然，学术界一般最关心 100 个回合的平均回合奖励。

对于有些任务，还会指定一个参考的回合奖励值，当连续 100 个回合的奖励大于指定的值时，则认为该任务被解决了。


# Gym 的使用方法
官方手册: https://www.gymlibrary.dev/

```python
env = gym.make("环境名")   # 取得环境
env.reset()               # 重置/初始化环境
env.step(action)          # 执行动作
env.render()              # 显示环境
env.close()               # 关闭环境
```